### ISSUE TITLE
git annex enableremote dropbox takes forever

### ISSUE THREAD

**Issue by fiatjaf** [TobiasTheViking/dropboxannex#3]
I don't know if this is an issue with dropboxannex, git annex or my setup, but after creating the "dropbox" remote in one machine and syncing, I'm trying to enable it in the other machine, and it's been two hours and the command is still stuck there:

```
fiatjaf@spooner ~/annex> git annex enableremote dropbox
enableremote dropbox 
```

**Comment by fiatjaf** [comment]
Well, after sending a SIGINT I got the following error report:

```
enableremote dropbox Traceback (most recent call last):
                                                         File "/usr/local/bin/git-annex-remote-dropbox", line 404, in <module>
                    common.startRemote()
                                          File "/home/fiatjaf/dropboxannex/lib/CommonFunctions.py", line 551, in startRemote
                  sys.modules["__main__"].initremote(line)
                                                            File "/usr/local/bin/git-annex-remote-dropbox", line 322, in initremote
                         stored_creds = login({})
                                                   File "/usr/local/bin/git-annex-remote-dropbox", line 53, in login
          webbrowser.open(url, True, True)
                                            File "/usr/lib/python2.7/webbrowser.py", line 61, in open
                                                                                                     fish: Job 1, “git annex enableremote dropbox” terminated by signal SIGINT (Quit request from job control (^C))
                                                                                                         if browser.open(url, new, autoraise):
  File "/usr/lib/python2.7/webbrowser.py", line 179, in open
    return not p.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

which means dropboxannex was trying to open a browser? If it is so, it couldn't, because this second repo is on a VPS I am accessing through ssh. But I already authorized it in my home computer, when I created it, so I don't understand.

**Comment by swappysh** [comment]
I am also stuck with this error, initiating remote takes forever
